# Generated by Django 5.0.6 on 2024-06-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='salaeData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('saleDate', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
