# Generated by Django 5.0.6 on 2024-06-24 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='salaeData',
            new_name='salesData',
        ),
    ]
